# Generated by Django 5.0.3 on 2024-03-26 01:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_service_delete_employees'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Service',
            new_name='Employees',
        ),
    ]
